In [1]:
import pandas as pd

## Syntax  - when do we use these?
- `()` - when calling a function or method; to create a tuple
- `{}` - when creating a dictionary or set 
- `[]` - when slicing an iterable; to create a list

### Tuple
- An ordered, immutable collection
- () are optional but prefered

In [2]:
tuple1 = ('Chris', 'Sobiya', 'Rene')

In [3]:
tuple2 = 'Chris', 'Sobiya', 'Rene'

In [4]:
print(tuple1)
print(tuple2)

('Chris', 'Sobiya', 'Rene')
('Chris', 'Sobiya', 'Rene')

In [5]:
tuple3 = tuple1 + tuple2
print(tuple3)

('Chris', 'Sobiya', 'Rene', 'Chris', 'Sobiya', 'Rene')

In [6]:
tuple3[0]

'Chris'

In [7]:
tuple3[0] = 'Steve'

TypeError: 'tuple' object does not support item assignment

### Set
- An unordered, collection of unique values
- Uses {}

In [ ]:
tuple3

In [8]:
set1 = set(tuple3)

In [9]:
set1

{'Chris', 'Rene', 'Sobiya'}

### Dictionary
- A collection of key:value pairs
- Uses {}

In [10]:
dict1 = {1111 : "April" , 2222 : "Jamal", 3333 : "Krystal", 4444 : "Lee", 5555 : "Carlos"}

In [11]:
dict1[1111]

'April'

In [12]:
dict1[1111] = "Fran"

In [13]:
dict1[1111]

'Fran'

In [14]:
dict1

{1111: 'Fran', 2222: 'Jamal', 3333: 'Krystal', 4444: 'Lee', 5555: 'Carlos'}

### List
- A ordered, mutable collection
- Uses []

### Simple list of postive integers

In [15]:
numbers = [78, 43, 9, 13, 50, 23]

In [16]:
numbers[0]

78

In [17]:
numbers[0] = 12

In [18]:
numbers

[12, 43, 9, 13, 50, 23]

In [19]:
names = ['Fran', 'Jamal', 'Krystal', 'Lee', 'Carlos']

In [20]:
new_dict = dict(zip(names, numbers))

In [21]:
new_dict

{'Fran': 12, 'Jamal': 43, 'Krystal': 9, 'Lee': 13, 'Carlos': 50}

In [22]:
names

['Fran', 'Jamal', 'Krystal', 'Lee', 'Carlos']

In [23]:
names.append('Ash')
names

['Fran', 'Jamal', 'Krystal', 'Lee', 'Carlos', 'Ash']

### Itterate through the list of numbers printing each in turn

In [24]:
for num in numbers:
    print('Number:', num)

Number: 12
Number: 43
Number: 9
Number: 13
Number: 50
Number: 23

### Find the largest number in a list greater than 0

In [25]:
largest = 0

for num in numbers:
    if num > largest:
        largest = num
        
print("The largest number is: ", largest)

The largest number is:  50

### Use a counter to find the largest number of any list of at least 1 item

In [26]:
count = 0

for num in numbers:
    if count == 0:
        largest = num
        
    if num > largest:
        largest = num
    
    count+=1

print("The largest number is: ", largest)

The largest number is:  50

### Read in the schools_clean.csv and look at the resulting dataframe

In [27]:
schools = pd.read_csv("schools_clean.csv")

In [28]:
schools

,level,name,zipcode,grade_k,grade_1,grade_2,grade_3,grade_4,grade_5,grade_6,...,hisp,p_islander,white,male,female,econ_disadv,disabled,limited_eng,lat,lng
0,Elementary School,A. Z. Kelley Elementary,37013,153.0,145.0,149.0,180.0,184.0,NaN,NaN,...,206,1.0,212.0,431,421,261,75.0,298.0,36.021817,-86.658848
1,Elementary School,Alex Green Elementary,37189,42.0,50.0,44.0,38.0,24.0,NaN,NaN,...,29,1.0,21.0,115,119,153,21.0,25.0,36.252961,-86.832229
2,Elementary School,Amqui Elementary,37115,84.0,93.0,77.0,87.0,84.0,NaN,NaN,...,209,1.0,57.0,223,235,246,51.0,143.0,36.273766,-86.703832
3,Elementary School,Andrew Jackson Elementary,37138,95.0,93.0,85.0,88.0,103.0,NaN,NaN,...,66,2.0,256.0,258,238,122,64.0,32.0,36.231585,-86.623775
4,High School,Antioch High School,37013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,806,1.0,387.0,1026,889,622,185.0,634.0,36.046675,-86.599418
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,Middle School,West End Middle,37205,NaN,NaN,NaN,NaN,NaN,125.0,138.0,...,28,1.0,247.0,261,242,112,113.0,27.0,36.131975,-86.824323
163,Elementary School,Westmeade Elementary,37205,72.0,101.0,80.0,88.0,81.0,NaN,NaN,...,74,1.0,178.0,238,184,132,48.0,63.0,36.091997,-86.894137
164,High School,Whites Creek High School,37189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,30,1.0,62.0,270,254,305,100.0,27.0,36.276645,-86.818833
165,Middle School,William Henry Oliver Middle,37211,NaN,NaN,NaN,NaN,NaN,231.0,271.0,...,158,3.0,437.0,487,498,252,112.0,231.0,36.020174,-86.712207
166,Middle School,Wright Middle,37211,NaN,NaN,NaN,NaN,NaN,188.0,216.0,...,534,1.0,104.0,443,367,400,75.0,536.0,36.100109,-86.734133

### Use iterrows to iterate though the dataframe, then, depending on school level, note the population of the highest grade served.
### Use a '-1' to note any row that does not work

In [29]:
for index, row in schools.iterrows():
    if row.level == "Elementary School":
        schools.loc[index, 'highest_grade'] = schools.loc[index, 'grade_4']
    elif row.level == "Middle School":
        schools.loc[index, 'highest_grade'] = schools.loc[index, 'grade_8']
    elif row.level == "High School":
        schools.loc[index, "highest_grade"] = schools.loc[index, 'grade_12']
    else:
        schools.loc[index, "highest_grade"] = -1

In [30]:
schools

,level,name,zipcode,grade_k,grade_1,grade_2,grade_3,grade_4,grade_5,grade_6,...,p_islander,white,male,female,econ_disadv,disabled,limited_eng,lat,lng,highest_grade
0,Elementary School,A. Z. Kelley Elementary,37013,153.0,145.0,149.0,180.0,184.0,NaN,NaN,...,1.0,212.0,431,421,261,75.0,298.0,36.021817,-86.658848,184.0
1,Elementary School,Alex Green Elementary,37189,42.0,50.0,44.0,38.0,24.0,NaN,NaN,...,1.0,21.0,115,119,153,21.0,25.0,36.252961,-86.832229,24.0
2,Elementary School,Amqui Elementary,37115,84.0,93.0,77.0,87.0,84.0,NaN,NaN,...,1.0,57.0,223,235,246,51.0,143.0,36.273766,-86.703832,84.0
3,Elementary School,Andrew Jackson Elementary,37138,95.0,93.0,85.0,88.0,103.0,NaN,NaN,...,2.0,256.0,258,238,122,64.0,32.0,36.231585,-86.623775,103.0
4,High School,Antioch High School,37013,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,387.0,1026,889,622,185.0,634.0,36.046675,-86.599418,448.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
162,Middle School,West End Middle,37205,NaN,NaN,NaN,NaN,NaN,125.0,138.0,...,1.0,247.0,261,242,112,113.0,27.0,36.131975,-86.824323,104.0
163,Elementary School,Westmeade Elementary,37205,72.0,101.0,80.0,88.0,81.0,NaN,NaN,...,1.0,178.0,238,184,132,48.0,63.0,36.091997,-86.894137,81.0
164,High School,Whites Creek High School,37189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,1.0,62.0,270,254,305,100.0,27.0,36.276645,-86.818833,129.0
165,Middle School,William Henry Oliver Middle,37211,NaN,NaN,NaN,NaN,NaN,231.0,271.0,...,3.0,437.0,487,498,252,112.0,231.0,36.020174,-86.712207,239.0
166,Middle School,Wright Middle,37211,NaN,NaN,NaN,NaN,NaN,188.0,216.0,...,1.0,104.0,443,367,400,75.0,536.0,36.100109,-86.734133,193.0

### Next we want to use a dictionary to act as a counter too see the frequency of languages used in a set of 100 tweets.   Please note, this is just an example of how, and this could more easily be done with a value_counts().

In [34]:
tweets = pd.read_csv('./data/tweets.csv')
tweets.head()

,contributors,coordinates,created_at,entities,extended_entities,favorite_count,favorited,filter_level,geo,id,...,quoted_status_id,quoted_status_id_str,retweet_count,retweeted,retweeted_status,source,text,timestamp_ms,truncated,user
0,NaN,NaN,Tue Mar 29 23:40:17 +0000 2016,"{'hashtags': [], 'user_mentions': [{'screen_na...","{'media': [{'sizes': {'large': {'w': 1024, 'h'...",0,False,low,NaN,714960401759387648,...,NaN,NaN,0,False,"{'retweeted': False, 'text': "".@krollbondratin...","<a href=""http://twitter.com"" rel=""nofollow"">Tw...",RT @bpolitics: .@krollbondrating's Christopher...,1459294817758,False,"{'utc_offset': 3600, 'profile_image_url_https'..."
1,NaN,NaN,Tue Mar 29 23:40:17 +0000 2016,"{'hashtags': [{'text': 'cruzsexscandal', 'indi...","{'media': [{'sizes': {'large': {'w': 500, 'h':...",0,False,low,NaN,714960401977319424,...,NaN,NaN,0,False,"{'retweeted': False, 'text': '@dmartosko Cruz ...","<a href=""http://twitter.com"" rel=""nofollow"">Tw...",RT @HeidiAlpine: @dmartosko Cruz video found.....,1459294817810,False,"{'utc_offset': None, 'profile_image_url_https'..."
2,NaN,NaN,Tue Mar 29 23:40:17 +0000 2016,"{'hashtags': [], 'user_mentions': [], 'symbols...",NaN,0,False,low,NaN,714960402426236928,...,NaN,NaN,0,False,NaN,"<a href=""http://www.facebook.com/twitter"" rel=...",Njihuni me ZonjÃ«n Trump !!! | Ekskluzive http...,1459294817917,False,"{'utc_offset': 7200, 'profile_image_url_https'..."
3,NaN,NaN,Tue Mar 29 23:40:17 +0000 2016,"{'hashtags': [], 'user_mentions': [], 'symbols...",NaN,0,False,low,NaN,714960402367561730,...,7.149239e+17,7.149239e+17,0,False,NaN,"<a href=""http://twitter.com/download/android"" ...",Your an idiot she shouldn't have tried to grab...,1459294817903,False,"{'utc_offset': None, 'profile_image_url_https'..."
4,NaN,NaN,Tue Mar 29 23:40:17 +0000 2016,"{'hashtags': [], 'user_mentions': [{'screen_na...",NaN,0,False,low,NaN,714960402149416960,...,NaN,NaN,0,False,"{'retweeted': False, 'text': 'The anti-America...","<a href=""http://twitter.com/download/iphone"" r...",RT @AlanLohner: The anti-American D.C. elites ...,1459294817851,False,"{'utc_offset': -18000, 'profile_image_url_http..."

In [35]:
tweets.columns

Index(['contributors', 'coordinates', 'created_at', 'entities',
       'extended_entities', 'favorite_count', 'favorited', 'filter_level',
       'geo', 'id', 'id_str', 'in_reply_to_screen_name',
       'in_reply_to_status_id', 'in_reply_to_status_id_str',
       'in_reply_to_user_id', 'in_reply_to_user_id_str', 'is_quote_status',
       'lang', 'place', 'possibly_sensitive', 'quoted_status',
       'quoted_status_id', 'quoted_status_id_str', 'retweet_count',
       'retweeted', 'retweeted_status', 'source', 'text', 'timestamp_ms',
       'truncated', 'user'],
      dtype='object')

In [36]:
tweets.lang.value_counts()

lang
en     97
und     2
et      1
Name: count, dtype: int64

In [37]:
lang_dict = {}

for lang in tweets.lang:
    if lang not in lang_dict:
        lang_dict[lang] = 1
    else:
        lang_dict[lang]+=1

In [38]:
lang_dict

{'en': 97, 'et': 1, 'und': 2}

### Create a function that takes a temperature in Fahrenheit and return that temperature in Celcius

In [39]:
def temp_switch(temp):
    
    celcius = (temp - 32) * 5/9
        
    return celcius

In [40]:
temp_switch(0)

-17.77777777777778

### Create a function that accepts 2 arguements and give the largest number between 1 and x that evenly goes into y.

In [41]:
def moddy(x,y):
    
    highest = 0
    for i in range(1, x):
        
        if y%i == 0:
            highest = i
    
    return(highest)

### Test our function

In [42]:
moddy(13, 28)

7

# End of Instruction

### Read in the hofplayers data

### Create a loop that goes through each row of the dataframe to see if that players birth country and death country were the same.
### If they were, then see if the birth state and death state were the same. if they were check to see if the birth city and death city are the same
### Each players should be categorized Either: "Same Country", "Same State", "Same City", "Unknown"

### Create a counter dictionary that counts the number of player in the hall of fame by state